import { recommended as effectTsgoRecommended } from "@effect/tsgo/oxlint-presets";
import { defineConfig } from "oxlint";
import { recommended as effectRecommended } from "oxlint-plugin-effect/presets/recommended";
import core from "ultracite/oxlint/core";

export default defineConfig({
  extends: [core, effectTsgoRecommended],
  ignorePatterns: [
    ".agents/skills/**",
    ".claude/skills/**",
    ".playbook/**",
    ".bootstrap/**",
    ".output/**",
    "build/**",
    "coverage/**",
    "dist/**",
    "packages/backend/confect/_generated/**",
    "packages/backend/convex/**",
  ],
  jsPlugins: ["oxlint-plugin-effect/plugin"],
  options: {
    typeAware: true,
  },
  rules: {
    ...effectRecommended,
    "effect/noTernary": "off",
    "effecttsgo/async-function": "off",
    "effecttsgo/crypto-random-uuid": "off",
    "effecttsgo/crypto-random-uuid-in-effect": "off",
    "effecttsgo/global-console": "off",
    "effecttsgo/global-console-in-effect": "off",
    "effecttsgo/global-date": "off",
    "effecttsgo/global-date-in-effect": "off",
    "effecttsgo/global-fetch": "off",
    "effecttsgo/global-fetch-in-effect": "off",
    "effecttsgo/global-random": "off",
    "effecttsgo/global-random-in-effect": "off",
    "effecttsgo/global-timers": "off",
    "effecttsgo/global-timers-in-effect": "off",
    "effecttsgo/new-promise": "off",
    "effecttsgo/node-builtin-import": "off",
    "effecttsgo/prefer-schema-over-json": "off",
    "effecttsgo/process-env": "off",
    "effecttsgo/process-env-in-effect": "off",
    "effecttsgo/try-catch-in-effect-gen": "off",
    "consistent-return": "off",
    "curly": "off",
    "eslint/no-await-in-loop": "off",
    "eslint/no-plusplus": "off",
    "eslint/prefer-named-capture-group": "off",
    "eslint/prefer-destructuring": "off",
    "eslint/prefer-template": "off",
    "eslint/require-await": "off",
    "eslint/sort-keys": "off",
    "func-style": "off",
    "import/consistent-type-specifier-style": "off",
    "no-use-before-define": ["error", { "functions": false, "typedefs": false }],
    "promise/prefer-await-to-callbacks": "off",
    "promise/prefer-await-to-then": "off",
    "typescript/consistent-type-definitions": ["error", "type"],
    "typescript/no-non-null-assertion": "off",
    "typescript/no-unsafe-type-assertion": "off",
    "typescript/strict-boolean-expressions": "off",
    "typescript/strict-void-return": "off",
    "unicorn/import-style": "off",
    "unicorn/no-array-reverse": "off",
    "unicorn/no-array-sort": "off",
    "unicorn/no-await-expression-member": "off",
  },
});
